global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'go-task-api'
    static_configs:
      - targets: ['localhost:8080']

remote_write:
  - url: https://prometheus-prod-xx.grafana.net/api/prom/push
    basic_auth:
      username: YOUR_INSTANCE_ID
      password: YOUR_API_KEY
