global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'go-task-api'
    scheme: https
    static_configs:
      - targets: ['task-management-system-production-b62d.up.railway.app']

remote_write:
  - url: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push
    basic_auth:
       username: ${PROM_USERNAME}
      password: ${PROM_PASSWORD}